"""
PlatformIO pre-build script.
Assembles src/page.h from ui/index.html + ui/style.css + ui/app.js.
Edit the source files in ui/; never edit src/page.h directly.
"""
import os
Import("env")  # noqa: F821 — injected by PlatformIO SCons

def build_page(source, target, env):
    root    = env["PROJECT_DIR"]
    ui_dir  = os.path.join(root, "ui")
    out     = os.path.join(root, "src", "page.h")

    with open(os.path.join(ui_dir, "index.html"), encoding="utf-8") as f:
        html = f.read()
    with open(os.path.join(ui_dir, "style.css"), encoding="utf-8") as f:
        css = f.read()
    with open(os.path.join(ui_dir, "app.js"), encoding="utf-8") as f:
        js = f.read()

    html = html.replace("<link rel=stylesheet href=style.css>",
                        "<style>" + css.rstrip() + "</style>")
    html = html.replace("<script src=app.js></script>",
                        "<script>" + js.rstrip() + "</script>")

    page_h = (
        "#pragma once\n"
        "#include <pgmspace.h>\n"
        "\n"
        "// Generated by build_page.py — do not edit directly.\n"
        "// Source: ui/index.html + ui/style.css + ui/app.js\n"
        'static const char PAGE[] PROGMEM = R"HTML(' + html + ')HTML";\n'
    )

    # Only write if content changed — avoids triggering a full rebuild on every
    # pio run when the UI sources haven't changed.
    existing = ""
    if os.path.exists(out):
        with open(out, encoding="utf-8") as f:
            existing = f.read()
    if page_h != existing:
        with open(out, "w", encoding="utf-8") as f:
            f.write(page_h)
        print(f"build_page.py: wrote src/page.h ({len(html)} bytes)")
    else:
        print("build_page.py: src/page.h unchanged")

env.AddPreAction("buildprog", build_page)
