"""
PlatformIO pre-build script.
Assembles src/page.h from ui/ source files.
Edit files in ui/; never edit src/page.h directly.
"""
import os
Import("env")  # noqa: F821 — injected by PlatformIO SCons

CSS_FILES = [
    "css/base.css",
    "css/sliders.css",
    "css/buttons.css",
    "css/modal.css",
    "css/themes.css",
    "css/presets.css",
    "css/sheet.css",
    "css/ai.css",
]

JS_FILES = [
    "js/globals.js",
    "js/ui.js",
    "js/lang.js",
    "js/state.js",
    "js/sliders.js",
    "js/presets.js",
    "js/ota.js",
    "js/ai.js",
    "js/ws.js",
]

def read(path):
    with open(path, encoding="utf-8") as f:
        return f.read()

def build_page(source, target, env):
    root   = env["PROJECT_DIR"]
    ui     = os.path.join(root, "ui")
    out    = os.path.join(root, "src", "page.h")

    css = "".join(read(os.path.join(ui, p)) for p in CSS_FILES).rstrip()
    js  = "".join(read(os.path.join(ui, p)) for p in JS_FILES).rstrip()

    html = read(os.path.join(ui, "index.html"))

    # Replace multi-link/script placeholders with single inlined blocks.
    # index.html lists individual <link> and <script> tags for browser preview;
    # we collapse them into one <style> and one <script> for the PROGMEM blob.
    import re
    html = re.sub(r'(<link rel=stylesheet href=css/[^>]+>\n?)+',
                  "<style>" + css + "</style>", html, count=1)
    html = re.sub(r'(<script src=js/[^>]+></script>\n?)+',
                  "<script>" + js + "</script>", html, count=1)

    page_h = (
        "#pragma once\n"
        "#include <pgmspace.h>\n"
        "\n"
        "// Generated by build_page.py — do not edit directly.\n"
        "// Sources: ui/index.html  ui/css/*.css  ui/js/*.js\n"
        'static const char PAGE[] PROGMEM = R"HTML(' + html.rstrip() + ')HTML";\n'
    )

    existing = ""
    if os.path.exists(out):
        with open(out, encoding="utf-8") as f:
            existing = f.read()
    if page_h != existing:
        with open(out, "w", encoding="utf-8") as f:
            f.write(page_h)
        print("build_page.py: wrote src/page.h ({} bytes)".format(len(html)))
    else:
        print("build_page.py: src/page.h unchanged")

env.AddPreAction("buildprog", build_page)
