[env:esp32s3]
platform = espressif32
board = esp32-s3-devkitc-1
framework = arduino
upload_port = /dev/cu.usbmodem*
monitor_port = /dev/cu.usbmodem*
upload_speed = 57600
upload_flags = --no-stub
monitor_speed = 115200
board_upload.flash_size = 4MB
board_build.partitions = partitions_ota_4mb.csv
lib_deps =
	fastled/FastLED @ ^3.9.4
	tzapu/WiFiManager @ ^2.0.17
build_flags =
	-D ARDUINO_USB_MODE=0
	-D ARDUINO_USB_CDC_ON_BOOT=0
extra_scripts = pre:get_version.py
