[env:esp32s3]
platform = espressif32@^7.0.0
board = esp32-s3-devkitc-1
framework = arduino
upload_port = /dev/cu.usbmodem*
monitor_port = /dev/cu.usbmodem*
upload_speed = 57600
upload_flags = --no-stub
monitor_speed = 115200
board_upload.flash_size = 4MB
board_build.partitions = partitions_ota_4mb.csv
lib_deps =
	fastled/FastLED @ ^3.9.4
	tzapu/WiFiManager @ ^2.0.17
	bblanchon/ArduinoJson @ ^7.0.4
	knolleary/PubSubClient @ ^2.8
build_unflags =
	-D ARDUINO_USB_MODE
	-D ARDUINO_USB_CDC_ON_BOOT
build_flags =
	-D ARDUINO_USB_MODE=0
	-D ARDUINO_USB_CDC_ON_BOOT=0
	-fstack-protector-strong
build_src_flags =
	-Wformat=2
	-Wformat-truncation
	-Werror
extra_scripts =
	pre:get_version.py
	pre:build_page.py
