import fs from 'fs';
import path from 'path';

const htmlPath = path.resolve('dist/index.html');
const manifestPath = path.resolve('manifest.json');
const outPath = path.resolve('../src/page.h');

const html = fs.readFileSync(htmlPath, 'utf-8');
const manifest_json = fs.existsSync(manifestPath) ? fs.readFileSync(manifestPath, 'utf-8') : '{}';

const page_h = `
#pragma once
#include <pgmspace.h>

// Generated by Vite + build_page.js — do not edit directly.
static const char PAGE[] PROGMEM = R"FLPG(${html})FLPG";
static const char MANIFEST_JSON[] PROGMEM = R"FLPG(${manifest_json})FLPG";
`;

fs.writeFileSync(outPath, page_h.trim() + '\n', 'utf-8');
console.log(`Wrote ${outPath} (${html.length} bytes HTML)`);
